language: node_js
node_js: 
  -'node'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433

